# Generated by Django 5.2.6 on 2025-09-29 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="starter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="started_topics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
