# Generated by Django 5.2.6 on 2025-09-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_alter_topic_starter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
