# Generated by Django 5.2.6 on 2025-10-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_alter_topic_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
