# Generated by Django 5.2.6 on 2025-10-06 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_topic_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="subject",
            field=models.CharField(max_length=500),
        ),
        migrations.RemoveField(
            model_name="topic",
            name="views",
        ),
        migrations.AddField(
            model_name="topic",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="viewed_topics", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
